drop table if exists orcamento cascade; -- (id, valor, data)
drop table if exists material cascade; -- (id, descricao)
drop table if exists orcamentosmateriais cascade; -- (id, quantidade, preco, #codOrc, #codMat)
drop table if exists homologado cascade; -- (id, #codAss, #codAloc, #codMat)
drop table if exists local cascade; -- (id, andar, setor, numero)
drop table if exists alocacao cascade; -- (id, dataalocacao, #codLocal, #codHom)
drop table if exists assinatura cascade; -- (id, dataassinatura, #codFun, #codHomo)
drop table if exists projeto cascade; -- (id, brevedescricao, datainicio)
drop table if exists funcionario cascade; -- (id, nome, idade, salario, dataegresso, dataingresso)
drop table if exists funcionariolocal cascade; -- (id, codfun, codlocal)
drop table if exists participacaoprojeto cascade; -- (id, datainicio, datafim, #codFun, #codProj)
drop table if exists tarefa cascade; -- (id, #codProj, brevedescricao, estado, prioridade, tempogasto, codfundono)
drop table if exists participacaotarefa cascade; -- (id, codfun, codtar, codsubtar)
drop table if exists coordenador cascade; -- (id, designacao, #codFun)
drop table if exists coordenadorprojeto cascade; -- (#codCoord, #codProj)
drop table if exists programador cascade; -- (id, #codFun)
drop table if exists linguagem cascade; -- (id, nome)
drop table if exists programadorlinguagem cascade; -- (id, dominio, #codProg, #codLing)
